import { NextResponse } from 'next/server'

export async function POST() {
  try {
    console.log('🔍 Attempting to create tours table...')
    
    const { supabase } = await import('@/lib/supabase')
    
    // Try to create the table directly
    const { error } = await supabase.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS tours (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title VARCHAR(255) NOT NULL,
          description TEXT NOT NULL,
          image TEXT NOT NULL,
          duration VARCHAR(50) NOT NULL,
          max_people VARCHAR(50) NOT NULL,
          price VARCHAR(50) NOT NULL,
          tag VARCHAR(100) NOT NULL,
          featured BOOLEAN DEFAULT FALSE,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        ALTER TABLE tours ENABLE ROW LEVEL SECURITY;
        
        CREATE POLICY IF NOT EXISTS "Tours are publicly viewable" ON tours
          FOR SELECT USING (true);
          
        CREATE POLICY IF NOT EXISTS "Authenticated users can manage tours" ON tours
          FOR ALL USING (auth.role() = 'authenticated');
      `
    })
    
    if (error) {
      console.log('❌ Could not create table via RPC:', error)
      
      // Return manual instructions
      return NextResponse.json({
        success: false,
        error: 'TABLE DOES NOT EXIST',
        details: 'The tours table has not been created in your Supabase database',
        fix: 'MANUAL SETUP REQUIRED',
        instructions: [
          '1. Go to your Supabase project dashboard',
          '2. Navigate to SQL Editor',
          '3. Click "New query"',
          '4. Copy the SQL from supabase/create-tours-table.sql',
          '5. Paste and click "Run"',
          '6. Restart your server: npm run dev'
        ],
        quickSql: `
          CREATE TABLE tours (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            image TEXT NOT NULL,
            duration VARCHAR(50) NOT NULL,
            max_people VARCHAR(50) NOT NULL,
            price VARCHAR(50) NOT NULL,
            tag VARCHAR(100) NOT NULL,
            featured BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );
        `
      })
    }
    
    return NextResponse.json({
      success: true,
      message: 'Table creation attempted',
      next_step: 'If this worked, try refreshing the admin page'
    })
  } catch (error) {
    return NextResponse.json({
      success: false,
      error: 'Setup failed',
      details: error instanceof Error ? error.message : 'Unknown error'
    })
  }
}
