-- Fix for tours table - Run this in Supabase SQL Editor

-- Create the tours table
CREATE TABLE IF NOT EXISTS tours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  duration VARCHAR(50) NOT NULL,
  max_people VARCHAR(50) NOT NULL,
  price VARCHAR(50) NOT NULL,
  tag VARCHAR(100) NOT NULL,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_tours_featured ON tours(featured);
CREATE INDEX IF NOT EXISTS idx_tours_tag ON tours(tag);
CREATE INDEX IF NOT EXISTS idx_tours_created_at ON tours(created_at);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_tours_updated_at
  BEFORE UPDATE ON tours
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE tours ENABLE ROW LEVEL SECURITY;

-- Allow public read access to tours
CREATE POLICY "Tours are publicly viewable" ON tours
  FOR SELECT USING (true);

-- Allow authenticated users to manage tours
CREATE POLICY "Authenticated users can manage tours" ON tours
  FOR ALL USING (auth.role() = 'authenticated');

-- Insert sample data (optional)
INSERT INTO tours (title, description, image, duration, max_people, price, tag, featured) VALUES
(
  'Panglao Island Hopping',
  'Explore Balicasag Island, snorkel with sea turtles, and visit the stunning Virgin Island sandbar.',
  'https://i.pinimg.com/1200x/ca/ab/91/caab91c6b26d164d8200815391de75c3.jpg',
  'Full Day',
  'Max 10',
  '₱3,500',
  'Island Hopping',
  true
),
(
  'Dolphin & Whale Watching',
  'Early morning dolphin watching cruise with Pamilacan Island snorkeling adventure.',
  'https://images.unsplash.com/photo-1570481662006-a3a1374699e8?q=80&w=384&h=310&fit=crop',
  'Half Day',
  'Max 8',
  '₱3,000',
  'Adventure',
  true
),
(
  'Philippine Tarsier Sanctuary',
  'Get up close with the world''s smallest primate in their natural rainforest habitat.',
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=384&h=310&fit=crop',
  'Half Day',
  'Max 12',
  '₱2,500',
  'Wildlife',
  true
)
ON CONFLICT DO NOTHING;
