-- QUICK FIX: Create tours table in Supabase
-- Copy this entire script and paste it in your Supabase SQL Editor

CREATE TABLE tours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  duration VARCHAR(50) NOT NULL,
  max_people VARCHAR(50) NOT NULL,
  price VARCHAR(50) NOT NULL,
  tag VARCHAR(100) NOT NULL,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE tours ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Tours are publicly viewable" ON tours
  FOR SELECT USING (true);

-- Allow authenticated users to manage tours
CREATE POLICY "Authenticated users can manage tours" ON tours
  FOR ALL USING (auth.role() = 'authenticated');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_tours_featured ON tours(featured);
CREATE INDEX IF NOT EXISTS idx_tours_tag ON tours(tag);
CREATE INDEX IF NOT EXISTS idx_tours_created_at ON tours(created_at);

-- Test the table by inserting a sample tour
INSERT INTO tours (title, description, image, duration, max_people, price, tag, featured)
VALUES (
  'Test Tour',
  'This is a test tour to verify the table works',
  'https://via.placeholder.com/400x300?text=Test+Tour',
  'Half Day',
  'Max 5',
  '₱500',
  'Test',
  false
);
